server:
  port: 9000
eureka:
  instance:
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 30
  client:
    # 是否注册到服务
    register-with-eureka: true
    # 不注册
    fetch-registry: true
    serviceUrl:
      defaultZone: http://service-center-3.com:${server.port}/eureka/,http://service-center-2.com:${server.port}/eureka/
