server:
  port: 9300
eureka:
  client:
    service-url:
      defaultZone: http://192.168.56.102:9800/eureka/
  instance:
    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    instance-id: ${eureka.instance.ip-address}:${server.port}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 15
    ip-address: 192.168.56.101
spring:
  application:
    name: hwj-meego-zipkin
#  cloud:
#    inetutils:
#      ignored-interfaces: ['VirtualBox.*']
#      preferred-networks:
#        - 192.168
#        - 10.0