server:
  port: 9300
eureka:
  client:
    service-url:
      defaultZone: http://192.168.56.101:9800/eureka/
  instance:
    prefer-ip-address: true
    instance-id: 192.168.56.101:${server.port}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 15
#    ip-address: 192.168.56.101
spring:
  application:
    name: hwj-meego-zipkin